# Generated by Django 6.0.1 on 2026-03-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_level_profile_rank_tier_profile_xp'),
        ('competitions', '0004_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_challenges', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=20),
        ),
    ]
