# Generated by Django 6.0.1 on 2026-03-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_challenge_opponent_alter_challenge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenger_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='opponent_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
