# Generated by Django 5.2.12 on 2026-04-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_challenge_challenger_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='region',
            field=models.CharField(choices=[('asia', 'Asia'), ('europe', 'Europe'), ('na', 'North America'), ('global', 'Global')], default='global', max_length=20),
        ),
    ]
