# Generated by Django 5.2.12 on 2026-04-25 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_worldchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldchatmessage',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='competitions.challenge'),
        ),
        migrations.AlterField(
            model_name='worldchatmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='worldchatmessage',
            name='message_type',
            field=models.CharField(choices=[('message', 'Message'), ('join_request', 'Join Request'), ('tournament_invite', 'Tournament Invite'), ('challenge_invite', 'Challenge Invite')], default='message', max_length=30),
        ),
    ]
