# Generated by Django 5.2.12 on 2026-04-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_worldchatmessage_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='tournament_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
