# Generated by Django 5.2.12 on 2026-04-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_competition_tournament_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='tournament_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
