# Generated by Django 5.2.12 on 2026-04-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_level_profile_rank_tier_profile_xp'),
        ('competitions', '0012_matchmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='competitions.competition')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_messages', to='accounts.profile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
