# Generated by Django 5.2.12 on 2026-04-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_level_profile_rank_tier_profile_xp'),
        ('competitions', '0013_competitionmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='matchmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_messages', to='accounts.profile'),
        ),
    ]
